### ISSUE TITLE
PATCH method is not currently supported

### ISSUE THREAD

**Issue by AlexDobeck** [Nike-Inc/lambda-router#4]
PATCH is currently not supported by this library, while being a valid http method definition:
https://tools.ietf.org/html/rfc5789

This method is particularly helpful in RESTful API design, most notably when working with JSON in such a way as to benefit from a Merge Patch:
https://tools.ietf.org/html/rfc7386

**Comment by AlexDobeck** [comment]
I've submitted a PR containing a proposed enhancement to include an exported patch function to resolve this issue:

https://github.com/Nike-Inc/lambda-router/pull/5

**Comment by kyeotic** [comment]
published under `2.10.0`
